title: 环境学院
author: Mr.Hope
time: 2020年9月1日
content:
  - tag: list
    content:
      - text: 学院简介
        icon: about
        path: /intro/school/environment/intro

      - text: 专业介绍
        icon: intro
        path: /intro/school/environment/enroll

      - text: 科研平台
        icon: platform
        path: /intro/school/environment/platform

      - text: 实验教学示范中心
        icon: degree
        path: /intro/school/environment/teach

      - text: 实验中心
        icon: experiment
        path: /intro/school/environment/experiment

  - tag: copy
    header: 官网地址
    text: https://hjxy.nenu.edu.cn
