title: 环境学院
author: Mr.Hope
time: 2020年9月1日
content:
  - tag: list
    content:
      - text: 学院简介
        path: /intro/school/environment/intro

      - text: 专业
        path: /intro/school/environment/enroll
