app:
  title: 欢迎使用 in 东师
  content: 欢迎使用 in 东师。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 69 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。
main:
  title: 学校网络安全演练
  content: 目前学校正在开展网络安全演练，期间学校各网站可能会无响应，属正常现象。
guide/account/authorize/index:
  title: 目前新生账号仍在录入中
  content: 可能会有小部分人无法登录。另外目前学校正在开展网络安全演练，期间学校各网站可能会无响应。
guide/express/index:
  title: 开放时间
  content: 学校驿站于 8 月 20 日开始营业，早于此日期到达的快递会被退回。
