title: 首页
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: 希望工作室长期招新

  # - tag: list
  #   header: false
  #   content:
  #     - text: 招新详情
  #       url: page?path=other/hope-studio/invite

  - tag: title
    text: 此处有搜索👆 您可以对小程序内容进行查找

  - tag: text
    type: danger
    heading: 请各位研究生注意
    text:
      - 本小程序是 Mr.Hope 的个人制作，属于公益服务。
      - 各位都已经读过4年的本科的成年人了，所以我不会将诸位当小孩子惯着。
      - 请不要过来把我当学校骂，否则我会骂回去＋拉黑!
      - 请不要摆出一副臭脸像我欠你钱一样，否则我也不会搭理你直接拉黑!
      - 我很忙，我也有自己的事情要做，提问之前先搜索小程序，已有的内容我不会进行解答。另外我不保证回复的时效，我有空的时候自然会回。
      - 如果你确定你的问题无法通过小程序解决，欢迎通过下方按钮咨询我。

  - tag: advanced-list
    header: false
    content:
      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact

  - tag: list
    header: 使用必读
    content:
      - text: 小程序使用须知
        icon: about
        url: page?path=other/about/guide

      - text: 常见问题
        icon: faq
        path: guide/faq/

  - tag: grid
    header: 您可能想关注
    content:
      - text: 到校路线
        color: grey
        name: Arrival
        icon: locate
        path: /guide/arrival/

      - text: 新生报到
        color: orange
        name: Check
        icon: check
        path: guide/check/

      - text: 快递
        color: mauve
        name: Express
        icon: express
        path: guide/express/

      - text: 寝室
        color: grey
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: 食堂
        color: mauve
        name: Dining
        icon: dining
        path: guide/dining/

      - text: 超市
        color: olive
        name: Shop
        icon: shop
        path: guide/shop/

      - text: 洗浴
        color: red
        name: Bath
        icon: bath
        path: guide/bath/

      - text: 生活
        color: purple
        name: Life
        icon: life
        path: guide/life/

      - text: 账户
        color: blue
        name: Account
        icon: authorize
        path: guide/account/

      - text: 校园卡
        color: red
        name: Card
        icon: card
        path: guide/card/

      - text: 校园网
        color: purple
        name: Network
        icon: network
        path: guide/network/

      - text: 选课
        color: cyan
        name: Select
        icon: select
        path: guide/select/

      # - text: 疫情相关
      #   color: mauve
      #   name: Epidemic
      #   icon: virus
      #   path: guide/epidemic/

      # - text: 每日健康上报
      #   color: purple
      #   name: Report
      #   icon: apply
      #   path: guide/epidemic/miniprogram/

      # - text: 入学准备
      #   color: red
      #   name: Prepare
      #   icon: prepare
      #   path: guide/prepare/

      # - text: 需带物品
      #   color: olive
      #   name: Necessity
      #   icon: necessity
      #   path: guide/necessity/

      # - text: 专业介绍
      #   color: olive
      #   name: Major
      #   icon: about
      #   path: intro/school/major

      # - text: 学校介绍
      #   color: mauve
      #   name: Intro
      #   icon: about
      #   path: intro/about/

      # - text: 转专业
      #   color: orange
      #   name: Change Major
      #   icon: change
      #   path: guide/change-major/

      # - text: 学位
      #   color: blue
      #   name: Degree
      #   icon: degree
      #   path: guide/degree/

      # - text: 新生群
      #   color: purple
      #   name: QQ Group
      #   icon: qq-group
      #   path: guide/prepare/qq-group/

      # - text: 谨防诈骗
      #   color: blue
      #   name: Protection
      #   icon: alert
      #   path: guide/prepare/cheat

    footer: 更多内容请详见下方其他 Tab 页

  # - tag: text
  #   type: danger
  #   heading: 请各位研究生新生注意
  #   text:
  #     - 本小程序是 Mr.Hope 的个人制作，属于公益服务。
  #     - 各位都已经读过4年的本科的成年人了，所以我不会将诸位当小孩子惯着。
  #     - 请不要过来把我当学校骂，否则我会骂回去＋拉黑!
  #     - 请不要摆出一副臭脸像我欠你钱一样，否则我也不会搭理你直接拉黑!
  #     - 我很忙，我也有自己的事情要做，提问之前先搜索小程序，已有的内容我不会进行解答。另外我不保证回复的时效，我有空的时候自然会回。

  # - tag: text
  #   text:
  #     - 如果你的问题没能通过小程序解决，欢迎通过下方按钮咨询我。

  # - tag: advanced-list
  #   header: false
  #   content:
  #     - text: 联系 Mr.Hope
  #       icon: contact
  #       type: button
  #       openType: contact
