title: 申请流程
author: Mr.Hope
time: 2021年11月22日
shareable: true
content:
  - tag: title
    text: 资助申请流程

  - tag: p
    text: 入学后，学校统一组织资助对象认定，对于获得资助对象资格的家庭经济困难学生给予相应资助。

  - tag: title
    text: 资助对象申请流程

  - tag: img
    src: $img/subsidize/subsidize1.png

  - tag: title
    text: 勤工助学岗位申请流程

  - tag: img
    src: $img/subsidize/subsidize2.png
