title: 我的东师
id: user
grey: true
hidden: true
content:
  - tag: list
    content:
      - text: 使用指南
        icon: idea
        url: page?path=other/guide/

      - text: 更新日志
        icon: log
        url: page?path=other/log/

      - text: 关于
        icon: about
        url: about

  - tag: functional-list
    header: 设置
    content:
      - type: picker
        icon: theme
        text: 主题设置
        select:
          - ios
          - android
          - nenu
          - weui
        key: themeNum
        handler: updateTheme
        single: true

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 存储设置
        icon: file
        url: storage

  - tag: p
    heading: " "
    text:
      - 如果您还有什么疑问，欢迎加入 in 东师咨询群 (1139044856) 进行咨询。
      - 小程序都是 Mr.Hope 个人开发编写，现已花费 Mr.Hope 超 2200 小时，文字数量超过 57 万字，同时小程序服务器每年会产生开销。如果您觉得小程序很有帮助，欢迎您给予支持。
    style:
      color: "#888"
      font-size: 14px

  - tag: functional-list
    content:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: 加入 in 东师咨询群
        icon: qq-group
        type: button
        openType: openGroupProfile
        groupId: "1139044856"

      - text: 添加 Mr.Hope 好友
        icon: qq
        type: button
        openType: addFriend
        openId: "868D7B2F0C609B4285698EAB77A47BA1"

      - text: 添加到桌面
        icon: send
        type: button
        handler: addToDesktop
