title: 功能大厅
id: function
grey: true
hidden: true
content:
  # - tag: card
  #   cover: $img/tab/headphone.jpg
  #   title: 音悦东师
  #   logo: cd
  #   url: music

  - tag: card
    cover: $img/tab/calendar.jpg
    title: 校历
    logo: calendar
    url: calendar

  - tag: card
    cover: $img/tab/sport-field.jpg
    title: 体测计算器
    logo: calculate
    url: PEcal
