title: 功能大厅
id: function
grey: true
hidden: true
content:
  - tag: card
    src: https://mp.innenu.com/img/tab/map.jpg
    title: 校园地图
    logo: map
    url: map

  # - tag: card
  #   type: page
  #   src: https://mp.innenu.com/img/tab/headphone.jpg
  #   title: 音悦东师
  #   logo: cd
  #   url: music

  - tag: card
    src: https://mp.innenu.com/img/tab/calendar.jpg
    title: 校历
    logo: calendar
    url: calendar

  - tag: card
    src: https://mp.innenu.com/img/tab/sport-field.jpg
    title: 体测计算器
    logo: calculate
    url: PEcal

  # - tag: card
  #   type: page
  #   src: https://mp.innenu.com/img/tab/wechat.jpg
  #   title: 校园公众号
  #   logo: account
  #   url: account
