title: 我的东师
id: user
grey: true
hidden: true
content:
  - tag: advanced-list
    content:
      - type: picker
        icon: theme
        text: 主题设置
        select:
          - ios
          - android
          - nenu
          - weui
        key: themeNum
        handler: updateTheme
        single: true

      - text: 权限设置
        icon: setting
        url: auth

      - text: 存储设置
        icon: setting
        url: storage

      - text: 更新日志
        icon: log
        url: log

      - text: 关于
        icon: about
        url: about

  - tag: advanced-list
    content:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact

      - text: 添加到桌面
        icon: send
        type: button
        openType: addToDesktop
