title: 首页
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: 希望工作室长期招新

  # - tag: list
  #   header: false
  #   items:
  #     - text: 招新详情
  #       url: page?path=Ohope-studio/invite

  # - tag: title
  #   text: 此处有搜索👆 您可以对小程序内容进行查找

  - tag: grid
    header: 您可能想关注
    items:
      - text: 校历
        color: mauve
        name: Calendar
        icon: calendar
        url: calendar

      - text: 火车票购买
        color: blue
        name: Ticket
        icon: train
        url: guide/traffic/train/

      - text: 课程
        color: orange
        name: Course
        icon: content
        path: guide/course/

      - text: 教务系统
        color: red
        name: System
        icon: system
        path: guide/system/

      - text: 学习
        color: mauve
        name: Study
        icon: study
        path: guide/study/

      - text: 图书馆
        color: blue
        name: Library
        icon: library
        path: intro/apt/library/

      - text: 校内考试
        color: olive
        name: Test
        icon: test
        path: guide/test/

      - text: 生活
        color: olive
        name: Life
        icon: life
        path: guide/life/

    footer: 更多内容请详见下方其他 Tab 页
