title: 我的东师
id: user
grey: true
hidden: true
content:
  - tag: list
    content:
      - text: 小程序使用指南
        icon: idea
        url: page?path=other/guide/

      - text: 内容更新日志
        icon: log
        url: page?path=other/content-log/

      - text: 小程序更新日志
        icon: log
        url: log

      - text: 关于
        icon: about
        url: about

  - tag: functional-list
    header: 设置
    content:
      - type: picker
        icon: theme
        text: 主题设置
        select:
          - ios
          - android
          - nenu
          - weui
        key: themeNum
        handler: updateTheme
        single: true

      - text: 权限设置
        icon: setting
        url: auth

      - text: 存储设置
        icon: setting
        url: storage

  - tag: functional-list
    content:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
