title: 城乡居民基本医疗保险
author: Mr.Hope
time: 2021年9月13日
shareable: true
content:
  - tag: text
    text:
      - 学校每年都会组织学生办理“长春市城乡居民基本医疗保险”。

  - tag: text
    type: info
    heading: 城镇居民基本医疗保险
    text: 城镇居民基本医疗保险是社会医疗保险的组成部分，采取以政府为主导，以居民个人（家庭）缴费为主，政府适度补助为辅的筹资方式，按照缴费标准和待遇水平相一致的原则，为城镇居民提供医疗需求的医疗保险制度。

  - tag: text
    type: tip
    text:
      - 入校前已缴纳的城乡居民基本医疗保险的结束时间为入学年底，所以无需担心保险的断缴问题。
      - 学校在 10 月后才会开展保险的统计、信息录入和收缴工作。

  - tag: title
    text: 信息录入

  - tag: p
    text:
      - 保险信息录入由各辅导员负责，通过学校与医保局进行联系，将学生保险经办机构改为“长春市市本级社会医疗保险管理局”。

  - tag: title
    text: 缴费标准

  - tag: text
    type: info
    heading: 2022年度收费标准
    text:
      - 230 元/人/年

  - tag: text
    type: note
    heading: 困难学生
    text:
      - 由长春市相关部门认定的符合参保资助条件的困难学生城镇居民基本医疗保险个人缴纳标准为 100 元 (享受 130 元资助)。

  - tag: title
    text: 城乡居民医保缴费方式与时间

  - tag: text
    text:
      - 请关注辅导员的通知，并在通知规定的时间内完成缴费。
      - 缴费通过“吉林税务社保缴费”小程序进行缴费。

  - tag: card
    title: 城乡居民医保缴费
    options:
      appId: wx2bd3e1deb552a91c
      path: pages/index/index

  - tag: img
    src: $img/check/insurance-base-pay.jpg
    env:
      - qq

  - tag: text
    type: warning
    text: 缴费时请确认自己的保险经办机构为“长春市市本级社会医疗保险管理局”!

  - tag: title
    text: 保险报销

  - tag: text
    type: info
    heading: 请参见长春市城乡居民基本医疗保险报销
    path: reimburse
