# 上次更新于 9/9 17:37
all: 920
donations:
  - - noveau
    - 227.48
  - - 悠然
    - 20
  - - 妖精哪里跑
    - 2
  - - 小凡
    - 16
  - - 红鼻子小黑
    - 8
  - - Administrator
    - 39.68
  - - 天天发财
    - 6
  - - WANG-
    - 8
  - - opviuivqo
    - 2
  - - 黄浦妹妹
    - 50
  - - 是小明啊
    - 8.8
  - - 寒冬为阳
    - 18
  - - Alory
    - 2
  - - 社会你龙哥
    - 20
  - - 杨家有女初长成
    - 6
  - - 柳棉
    - 2
  - - crq007
    - 100
