title: 首页
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: 希望工作室长期招新

  # - tag: list
  #   header: false
  #   items:
  #     - text: 招新详情
  #       url: page?path=Ohope-studio/invite

  # - tag: title
  #   text: 此处有搜索👆 您可以对小程序内容进行查找

  - tag: grid
    header: 您可能想关注
    items:
      - text: 学生组织
        color: blue
        name: Orgnazation
        icon: student-org
        path: guide/organization/

      - text: 社团
        color: orange
        name: Association
        icon: association
        path: guide/association/

      - text: 入学活动
        color: purple
        name: Activity
        icon: activity
        path: guide/activity/

      - text: 快递
        color: mauve
        name: Express
        icon: express
        path: guide/express/

      - text: 寝室
        color: grey
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: 食堂
        color: mauve
        name: Dining
        icon: dining
        path: guide/dining/

      - text: 超市
        color: olive
        name: Shop
        icon: shop
        path: guide/shop/

      - text: 洗浴
        color: red
        name: Bath
        icon: bath
        path: guide/bath/

      - text: 生活
        color: purple
        name: Life
        icon: life
        path: guide/life/

      - text: 账户
        color: blue
        name: Account
        icon: authorize
        path: guide/account/

      - text: 校园卡
        color: red
        name: Card
        icon: card
        path: guide/card/

      - text: 校园网
        color: purple
        name: Network
        icon: network
        path: guide/network/

    footer: 更多内容请详见下方其他 Tab 页

  - tag: card
    cover: $img/tab/map.jpg
    title: 校园地图与导航
    logo: map
    url: map

  - tag: card
    cover: $img/tab/faq.png
    title: 常见问题
    logo: faq
    url: page?id=Gfaq/
