title: 首页
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: 希望工作室长期招新

  # - tag: list
  #   header: false
  #   content:
  #     - text: 招新详情
  #       url: page?path=other/hope-studio/invite

  # - tag: title
  #   text: 此处有搜索👆 您可以对小程序内容进行查找

  - tag: text
    type: info
    heading: 2022年春季学期本科生选课已开始
    text:
      - |-
        预选时间: 12月1日12:00至12月3日16:00
        12月7日10:00公布预选抽签结果
      - |-
        正选时间: 12月9日12:00至12月14日12:00
        本部校区正选 :12月9日12:00至12月13日12:00　　
        净月校区正选 :12月10日12:00至12月14日12:00　
      - |-
        退补选时间: 计划在3月7日－3月11日之间进行，具体时间另行通知

  - tag: grid
    header: 您可能想关注
    content:
      - text: 选课
        color: cyan
        name: Select
        icon: select
        path: guide/select/

      - text: 使用 IE 内核
        color: olive
        name: IE
        icon: ie
        path: guide/tip/ie/

      - text: 课程
        color: orange
        name: Course
        icon: content
        path: guide/course/

      - text: 教务系统
        color: red
        name: System
        icon: system
        path: guide/system/

      - text: 账户
        color: blue
        name: Account
        icon: authorize
        path: guide/account/

      - text: 校历
        color: mauve
        name: Calendar
        icon: calendar
        url: calendar

      - text: 生活
        color: olive
        name: Life
        icon: life
        path: guide/life/

      - text: 常见服务
        color: mauve
        name: Service
        icon: service
        path: guide/action/

      - text: 转专业
        color: red
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: 学习
        color: mauve
        name: Study
        icon: study
        path: guide/study/

      - text: 图书馆
        color: blue
        name: Library
        icon: library
        path: intro/apt/library/

      - text: 校内考试
        color: olive
        name: Test
        icon: test
        path: guide/test/

    footer: 更多内容请详见下方其他 Tab 页

  - tag: card
    cover: http://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc7fibAYDFBn7oAvOaEs00iblrOKaFWoIrqzQzoXXDPmHNjS9bm9ZUVQWB3149EYsjmQNS4jU1HzUW5Q/0?wx_fmt=jpeg
    title: 招纳小程序志愿者
    logo: $img/inNENU.png
    name: in东师
    url: page?path=other/guide/volunteer
