title: 360 安全浏览器的推荐设置
author: Mr.Hope
time: 2021年12月1日
shareable: true
content:
  - tag: text
    type: danger
    heading: 不建议使用 360 安全浏览器
    text:
      - 虽然 360 安全浏览器自带 IE 内核，可以使用 IE 11 兼容模式打开网页，而且下载安装很方便，但是它有远大于前述优点的缺点。
      - Mr.Hope 极其不推荐您安装 360。请您尽可能选择下方的方案。

  - tag: list
    header: 替代方案
    content:
      - text: 使用 IETab 扩展程序
        icon: ie
        path: ietab/

      - text: 使用 Microsoft Edge 提供的 IE 兼容模式
        icon: edge
        path: msedge

  - tag: title
    text: 极其不推荐使用 360 安全浏览器的原因

  - tag: img
    src: $img/tip/360-evil.jpg
    desc: 界面展示

  - tag: list
    header: 详情
    content:
      - text: 不建议使用 360 安全浏览器的原因
        icon: alert
        path: 360-evil

  - tag: title
    text: 推荐修改的设置

  - tag: text
    text: 请点击右上角菜单，选择“设置”并进行如下修改。

  - tag: img
    src: $img/tip/360-settings-1.jpg

  - tag: img
    src: $img/tip/360-settings-2.jpg

  - tag: img
    src: $img/tip/360-settings-3.jpg

  - tag: img
    src: $img/tip/360-settings-4.jpg

  - tag: img
    src: $img/tip/360-settings-5.jpg

  - tag: img
    src: $img/tip/360-settings-6.jpg

  - tag: img
    src: $img/tip/360-settings-7.jpg

  - tag: img
    src: $img/tip/360-settings-8.jpg

  - tag: img
    src: $img/tip/360-settings-9.jpg

  - tag: img
    src: $img/tip/360-settings-after.jpg
    desc: 修改后
