title: 首页
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: 希望工作室长期招新

  # - tag: list
  #   header: false
  #   content:
  #     - text: 招新详情
  #       url: page?path=other/hope-studio/invite

  # - tag: title
  #   text: 此处有搜索👆 您可以对小程序内容进行查找

  - tag: card
    src: http://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc7z7Zaq7P7PRw8ycuI57XibfbicHbb0XzcXic0jTAyOGdp1cCrHHdP9VPG11sBJ9ic3mnJNzeN1gKwcEQ/0?wx_fmt=jpeg
    title: 警惕线上投票
    logo: https://mp.innenu.com/img/inNENU.png
    name: in东师
    url: page?path=other/cheat/vote

  - tag: grid
    header: 您可能想关注
    content:
      - text: 学生组织
        color: blue
        name: Orgnazation
        icon: student-org
        path: guide/organization/

      - text: 社团
        color: orange
        name: Association
        icon: association
        path: guide/association/

      - text: 入学活动
        color: purple
        name: Activity
        icon: activity
        path: guide/activity/

      - text: 生活
        color: olive
        name: Life
        icon: life
        path: guide/life/

    footer: 更多内容请详见下方其他 Tab 页
